### ISSUE TITLE
Moveit RobotCommander fails on kinetic

### ISSUE THREAD

**Issue by beatrizleon** [shadow-robot/sr_interface#234]
With the following error:
```
  File "/home/user/projects/shadow_robot/base/src/sr_interface/sr_robot_commander/src/sr_robot_commander/follow_warehouse_trajectory.py", line 5, in <module>
    from moveit_commander import RobotCommander
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/__init__.py", line 3, in <module>
    from planning_scene_interface import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/planning_scene_interface.py", line 48, in <module>
    import pyassimp
  File "/usr/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 23, in <module>
    from . import structs
ImportError: cannot import name structs
```

It is a known issue: https://github.com/ros-planning/moveit/issues/86

**Comment by beatrizleon** [comment]
As mentioned in the previous link, It can be fixed doing the following:

1) Pull the latest version from assimp. https://github.com/assimp/assimp.git and build it. 
2) Go to /port/PyAssimp in the source folder and run python setup.py install. This should create the necessary files in /usr/local/lib/python2.7/dist-packages/pyassimp.

**Comment by toliver** [comment]
Have you tried this approach using pip?
https://github.com/ros-planning/moveit/issues/86#issuecomment-272818055

**Comment by beatrizleon** [comment]
It doesn't work for me. It gives me the following output:
`Requirement already satisfied: pyassimp in /usr/lib/python2.7/dist-packages`

**Comment by toliver** [comment]
This also means that our tests are too basic, as jenkins is currently green.

**Comment by eborghi10** [comment]
Hi @beatrizleon, I tried to solve the same error like you mention above but I get an error I run the _setup.py_ script. The error says that can't found the ../../lib folder (and, of course, it's not there). 

I build the assimp package with:
`assymp/include/$ cmake ..`
`assymp/include/$ make`
`assymp/include/$ make install`

Are the previous instructions well implemented? I had no errors with that, so I think it's OK, but, I'm not sure how to fix it. 

Thanks in advance.

**Comment by eborghi10** [comment]
I solved it changing one line in the core.py file in the assimp package. Take a look [here](https://launchpadlibrarian.net/263969718/patch.txt).

**Comment by amaldo** [comment]
@eborghi10 : Thanks, that seems to be the easiest fix.

**Comment by ghost** [comment]
Hi tried it but it doesn't work.
 
Traceback (most recent call last):
  File "/home/humza/ros_ws_2/src/pr2_moveit_tutorials/scripts/move_group_python_interface_tutorial.py", line 44, in <module>
    import moveit_commander
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/__init__.py", line 3, in <module>
    from planning_scene_interface import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/planning_scene_interface.py", line 48, in <module>
    import pyassimp
  File "/usr/local/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/dist-packages/pyassimp/core.py", line 28, in <module>
    from . import structs
ImportError: cannot import name structs

**Comment by emigmo** [comment]
sudo pip install --upgrade pyassimp
update the pyassimp to 3.3
